/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ok.app;

import org.ok.protocols.Block;
import org.ok.protocols.CaesarCipher;
import org.ok.protocols.HMAC;

public class App {
    public static void main(String[] args) {
        String message = "hello, world!";

        CaesarCipher cipher = new CaesarCipher('B');

        System.out.println("Original: " + message);
        System.out.println("Encrypted: " + cipher.encrypt(message));
        System.out.println("Decrypted: " + cipher.decrypt(cipher.encrypt(message)));

        HMAC hmac = new HMAC();
        //hmac.testPrint();
        Block block = hmac.encode(new Block(message.getBytes().length, message), new Block("keykey".getBytes().length, "keykey"));
        for(char c : block.getData()){
            System.out.printf("%02x", (byte)c);
        }
    }
}
