/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.java-websocket:Java-WebSocket:1.6.0")
    implementation("org.apache.commons:commons-text")
    implementation(project(":communication"))
    implementation(project(":protocols"))
    implementation("org.whispersystems:curve25519-java:0.5.0")
    implementation("com.h2database:h2-mvstore:1.4.186")
}

application {
    // Define the main class for the application.
    mainClass = "org.ok.app.App"
}
