/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.java-websocket:Java-WebSocket:1.6.0")
    implementation("org.apache.commons:commons-text")
    implementation(project(":communication"))
    implementation(project(":protocols"))
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
