/*
 * This file was generated by the Gradle 'init' task.
 */

repositories {
    mavenCentral()
}

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation("org.whispersystems:curve25519-java:0.5.0")
    api(project(":protocols"))
}
